language: python
python:
  - "3.8"
install:
  - pip install -r requirements-dev.txt
  - python -m grpc.tools.protoc -I=bubbles/protobuf --python_out=bubbles/protobuf bubbles.proto
script:
  - flake8
  - pytest --cov-report term --cov=bubbles
after_success:
  - codecov